export const supportedBanks = [
    { code: '044', name: 'Access Bank' },
    { code: '023', name: 'Citibank Nigeria' },
    { code: '050', name: 'Ecobank Nigeria' },
    { code: '214', name: 'FCMB' },
    { code: '070', name: 'Fidelity Bank' },
    { code: '011', name: 'First Bank of Nigeria' },
    { code: '103', name: 'Globus Bank' },
    { code: '058', name: 'Guaranty Trust Bank (GTBank)' },
    { code: '030', name: 'Heritage Bank' },
    { code: '301', name: 'Jaiz Bank' },
    { code: '082', name: 'Keystone Bank' },
    { code: '090267', name: 'Kuda Bank' },
    { code: '50515', name: 'Moniepoint Microfinance Bank' },
    { code: '090175', name: 'Rubies Microfinance Bank' },
    { code: '221', name: 'Stanbic IBTC Bank' },
    { code: '232', name: 'Sterling Bank' },
    { code: '100', name: 'Suntrust Bank' },
    { code: '033', name: 'United Bank for Africa (UBA)' },
    { code: '032', name: 'Union Bank of Nigeria' },
    { code: '215', name: 'Unity Bank' },
    { code: '035', name: 'Wema Bank' },
    { code: '057', name: 'Zenith Bank' },
    { code: '999992', name: 'OPay' },
    { code: '999991', name: 'PalmPay' },
    { code: '999993', name: 'Paga' },
    { code: '090405', name: 'Sparkle Microfinance Bank' },
    { code: '526', name: 'Parallex Bank' },
    { code: '101', name: 'Providus Bank' },
];

export const internalWalletBank = { code: 'INTERNAL_WALLET', name: 'OPay Wallet' };
